{% set name = "qrtools" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qrtools-{{ version }}.tar.gz
  sha256: e6f0034ea884b8461ebff4bef2cf546fef4dfeca1e3948ac975f8f14fe45381a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pypng
    - zbar
    - pillow

test:
  imports:
    - qrtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/primetang/qrtools
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENCE
  summary: 'A suite of tools for handling QR codes.'
  description: |
    A suite of tools for handling QR codes.
  doc_url: https://github.com/primetang/qrtools
  dev_url: https://github.com/primetang/qrtools

extra:
  recipe-maintainers:
    - jan-janssen
